# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/tasarim.ui'
#
# Created: Thu Jul 23 01:18:02 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setEnabled(True)
        Dialog.resize(461, 400)
        Dialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.horizontalLayoutWidget = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 201, 381))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.SOL = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.SOL.setMargin(0)
        self.SOL.setObjectName(_fromUtf8("SOL"))
        self.sag_dik = QtGui.QVBoxLayout()
        self.sag_dik.setObjectName(_fromUtf8("sag_dik"))
        self.chkbxa_5v_1 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxa_5v_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbxa_5v_1.setObjectName(_fromUtf8("chkbxa_5v_1"))
        self.sag_dik.addWidget(self.chkbxa_5v_1)
        self.chkbxa_5v_2 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxa_5v_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbxa_5v_2.setObjectName(_fromUtf8("chkbxa_5v_2"))
        self.sag_dik.addWidget(self.chkbxa_5v_2)
        self.chkbxa_G1 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxa_G1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbxa_G1.setObjectName(_fromUtf8("chkbxa_G1"))
        self.sag_dik.addWidget(self.chkbxa_G1)
        self.chkbxa_14 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxa_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbxa_14.setObjectName(_fromUtf8("chkbxa_14"))
        self.sag_dik.addWidget(self.chkbxa_14)
        self.chkbxa_15 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxa_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbxa_15.setObjectName(_fromUtf8("chkbxa_15"))
        self.sag_dik.addWidget(self.chkbxa_15)
        self.chkbxa_18 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxa_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbxa_18.setObjectName(_fromUtf8("chkbxa_18"))
        self.sag_dik.addWidget(self.chkbxa_18)
        self.chkbxa_G2 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxa_G2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbxa_G2.setObjectName(_fromUtf8("chkbxa_G2"))
        self.sag_dik.addWidget(self.chkbxa_G2)
        self.chkbxa_23 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxa_23.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbxa_23.setObjectName(_fromUtf8("chkbxa_23"))
        self.sag_dik.addWidget(self.chkbxa_23)
        self.chkbxa_24 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxa_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbxa_24.setObjectName(_fromUtf8("chkbxa_24"))
        self.sag_dik.addWidget(self.chkbxa_24)
        self.chkbxa_G3 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxa_G3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbxa_G3.setObjectName(_fromUtf8("chkbxa_G3"))
        self.sag_dik.addWidget(self.chkbxa_G3)
        self.chkbxa_25 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxa_25.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbxa_25.setObjectName(_fromUtf8("chkbxa_25"))
        self.sag_dik.addWidget(self.chkbxa_25)
        self.chkbxa_08 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxa_08.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbxa_08.setObjectName(_fromUtf8("chkbxa_08"))
        self.sag_dik.addWidget(self.chkbxa_08)
        self.chkbxa_07 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxa_07.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbxa_07.setObjectName(_fromUtf8("chkbxa_07"))
        self.sag_dik.addWidget(self.chkbxa_07)
        self.chkbxa_SC = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxa_SC.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbxa_SC.setObjectName(_fromUtf8("chkbxa_SC"))
        self.sag_dik.addWidget(self.chkbxa_SC)
        self.chkbxa_G4 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxa_G4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbxa_G4.setObjectName(_fromUtf8("chkbxa_G4"))
        self.sag_dik.addWidget(self.chkbxa_G4)
        self.chkbxa_12 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxa_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbxa_12.setObjectName(_fromUtf8("chkbxa_12"))
        self.sag_dik.addWidget(self.chkbxa_12)
        self.chkbxa_G5 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxa_G5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbxa_G5.setObjectName(_fromUtf8("chkbxa_G5"))
        self.sag_dik.addWidget(self.chkbxa_G5)
        self.chkbxa_16 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxa_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbxa_16.setObjectName(_fromUtf8("chkbxa_16"))
        self.sag_dik.addWidget(self.chkbxa_16)
        self.chkbxa_20 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxa_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbxa_20.setObjectName(_fromUtf8("chkbxa_20"))
        self.sag_dik.addWidget(self.chkbxa_20)
        self.chkbxa_21 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxa_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkbxa_21.setObjectName(_fromUtf8("chkbxa_21"))
        self.sag_dik.addWidget(self.chkbxa_21)
        self.SOL.addLayout(self.sag_dik)
        self.sol_dik = QtGui.QVBoxLayout()
        self.sol_dik.setObjectName(_fromUtf8("sol_dik"))
        self.chkbxs_3v3_1 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxs_3v3_1.setObjectName(_fromUtf8("chkbxs_3v3_1"))
        self.sol_dik.addWidget(self.chkbxs_3v3_1)
        self.chkbxs_02 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxs_02.setObjectName(_fromUtf8("chkbxs_02"))
        self.sol_dik.addWidget(self.chkbxs_02)
        self.chkbxs_03 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxs_03.setObjectName(_fromUtf8("chkbxs_03"))
        self.sol_dik.addWidget(self.chkbxs_03)
        self.chkbxs_04 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxs_04.setObjectName(_fromUtf8("chkbxs_04"))
        self.sol_dik.addWidget(self.chkbxs_04)
        self.chkbxs_G1 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxs_G1.setObjectName(_fromUtf8("chkbxs_G1"))
        self.sol_dik.addWidget(self.chkbxs_G1)
        self.chkbxs_17 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxs_17.setObjectName(_fromUtf8("chkbxs_17"))
        self.sol_dik.addWidget(self.chkbxs_17)
        self.chkbxs_27 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxs_27.setObjectName(_fromUtf8("chkbxs_27"))
        self.sol_dik.addWidget(self.chkbxs_27)
        self.chkbxs_22 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxs_22.setObjectName(_fromUtf8("chkbxs_22"))
        self.sol_dik.addWidget(self.chkbxs_22)
        self.chkbxs_3v3_2 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxs_3v3_2.setObjectName(_fromUtf8("chkbxs_3v3_2"))
        self.sol_dik.addWidget(self.chkbxs_3v3_2)
        self.chkbxs_10 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxs_10.setObjectName(_fromUtf8("chkbxs_10"))
        self.sol_dik.addWidget(self.chkbxs_10)
        self.chkbxs_09 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxs_09.setObjectName(_fromUtf8("chkbxs_09"))
        self.sol_dik.addWidget(self.chkbxs_09)
        self.chkbxs_11 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxs_11.setObjectName(_fromUtf8("chkbxs_11"))
        self.sol_dik.addWidget(self.chkbxs_11)
        self.chkbxs_G2 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxs_G2.setObjectName(_fromUtf8("chkbxs_G2"))
        self.sol_dik.addWidget(self.chkbxs_G2)
        self.chkbxs_SD = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxs_SD.setObjectName(_fromUtf8("chkbxs_SD"))
        self.sol_dik.addWidget(self.chkbxs_SD)
        self.chkbxs_05 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxs_05.setObjectName(_fromUtf8("chkbxs_05"))
        self.sol_dik.addWidget(self.chkbxs_05)
        self.chkbxs_06 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxs_06.setObjectName(_fromUtf8("chkbxs_06"))
        self.sol_dik.addWidget(self.chkbxs_06)
        self.chkbxs_13 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxs_13.setObjectName(_fromUtf8("chkbxs_13"))
        self.sol_dik.addWidget(self.chkbxs_13)
        self.chkbxs_19 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxs_19.setObjectName(_fromUtf8("chkbxs_19"))
        self.sol_dik.addWidget(self.chkbxs_19)
        self.chkbxs_26 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxs_26.setObjectName(_fromUtf8("chkbxs_26"))
        self.sol_dik.addWidget(self.chkbxs_26)
        self.chkbxs_G3 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkbxs_G3.setObjectName(_fromUtf8("chkbxs_G3"))
        self.sol_dik.addWidget(self.chkbxs_G3)
        self.SOL.addLayout(self.sol_dik)
        self.verticalLayoutWidget_3 = QtGui.QWidget(Dialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(220, 10, 231, 381))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.SAG = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.SAG.setMargin(0)
        self.SAG.setObjectName(_fromUtf8("SAG"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.btn_uygula = QtGui.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_uygula.sizePolicy().hasHeightForWidth())
        self.btn_uygula.setSizePolicy(sizePolicy)
        self.btn_uygula.setObjectName(_fromUtf8("btn_uygula"))
        self.horizontalLayout_16.addWidget(self.btn_uygula)
        self.SAG.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btn_ac_3 = QtGui.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ac_3.sizePolicy().hasHeightForWidth())
        self.btn_ac_3.setSizePolicy(sizePolicy)
        self.btn_ac_3.setObjectName(_fromUtf8("btn_ac_3"))
        self.horizontalLayout_3.addWidget(self.btn_ac_3)
        self.btn_kapat = QtGui.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_kapat.sizePolicy().hasHeightForWidth())
        self.btn_kapat.setSizePolicy(sizePolicy)
        self.btn_kapat.setObjectName(_fromUtf8("btn_kapat"))
        self.horizontalLayout_3.addWidget(self.btn_kapat)
        self.SAG.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_50 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.horizontalLayout_17.addWidget(self.label_50)
        self.label_49 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.horizontalLayout_17.addWidget(self.label_49)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_51 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.horizontalLayout_18.addWidget(self.label_51)
        self.label_53 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.horizontalLayout_18.addWidget(self.label_53)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_57 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.horizontalLayout_20.addWidget(self.label_57)
        self.label_59 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.horizontalLayout_20.addWidget(self.label_59)
        self.verticalLayout_6.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_54 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.horizontalLayout_19.addWidget(self.label_54)
        self.label_56 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.horizontalLayout_19.addWidget(self.label_56)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.SAG.addLayout(self.verticalLayout_6)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.chkbxa_5v_1.setText(_translate("Dialog", "5v", None))
        self.chkbxa_5v_2.setText(_translate("Dialog", "5v", None))
        self.chkbxa_G1.setText(_translate("Dialog", "GND", None))
        self.chkbxa_14.setText(_translate("Dialog", "GPIO 14", None))
        self.chkbxa_15.setText(_translate("Dialog", "GPIO 15", None))
        self.chkbxa_18.setText(_translate("Dialog", "GPIO 18", None))
        self.chkbxa_G2.setText(_translate("Dialog", "GND", None))
        self.chkbxa_23.setText(_translate("Dialog", "GPIO 23", None))
        self.chkbxa_24.setText(_translate("Dialog", "GPIO 24", None))
        self.chkbxa_G3.setText(_translate("Dialog", "GND", None))
        self.chkbxa_25.setText(_translate("Dialog", "GPIO 25", None))
        self.chkbxa_08.setText(_translate("Dialog", "GPIO 08", None))
        self.chkbxa_07.setText(_translate("Dialog", "GPIO 07", None))
        self.chkbxa_SC.setText(_translate("Dialog", "ID_SC", None))
        self.chkbxa_G4.setText(_translate("Dialog", "GND", None))
        self.chkbxa_12.setText(_translate("Dialog", "GPIO 12", None))
        self.chkbxa_G5.setText(_translate("Dialog", "GND", None))
        self.chkbxa_16.setText(_translate("Dialog", "GPIO 16", None))
        self.chkbxa_20.setText(_translate("Dialog", "GPIO 20", None))
        self.chkbxa_21.setText(_translate("Dialog", "GPIO 21", None))
        self.chkbxs_3v3_1.setText(_translate("Dialog", "3v3", None))
        self.chkbxs_02.setText(_translate("Dialog", "GPIO 02", None))
        self.chkbxs_03.setText(_translate("Dialog", "GPIO 03", None))
        self.chkbxs_04.setText(_translate("Dialog", "GPIO 04", None))
        self.chkbxs_G1.setText(_translate("Dialog", "GND", None))
        self.chkbxs_17.setText(_translate("Dialog", "GPIO 17", None))
        self.chkbxs_27.setText(_translate("Dialog", "GPIO 27", None))
        self.chkbxs_22.setText(_translate("Dialog", "GPIO 22", None))
        self.chkbxs_3v3_2.setText(_translate("Dialog", "3v3", None))
        self.chkbxs_10.setText(_translate("Dialog", "GPIO 10", None))
        self.chkbxs_09.setText(_translate("Dialog", "GPIO 09", None))
        self.chkbxs_11.setText(_translate("Dialog", "GPIO 11", None))
        self.chkbxs_G2.setText(_translate("Dialog", "GND", None))
        self.chkbxs_SD.setText(_translate("Dialog", "ID_SD", None))
        self.chkbxs_05.setText(_translate("Dialog", "GPIO 05", None))
        self.chkbxs_06.setText(_translate("Dialog", "GPIO 06", None))
        self.chkbxs_13.setText(_translate("Dialog", "GPIO 13", None))
        self.chkbxs_19.setText(_translate("Dialog", "GPIO 19", None))
        self.chkbxs_26.setText(_translate("Dialog", "GPIO 26", None))
        self.chkbxs_G3.setText(_translate("Dialog", "GND", None))
        self.btn_uygula.setText(_translate("Dialog", "Uygula", None))
        self.btn_ac_3.setText(_translate("Dialog", "Kapat", None))
        self.btn_kapat.setText(_translate("Dialog", "Bilgi", None))
        self.label_50.setText(_translate("Dialog", "       3,3 V Çıkış Pini", None))
        self.label_49.setText(_translate("Dialog", "3v3", None))
        self.label_51.setText(_translate("Dialog", "           5 V Çıkış Pini", None))
        self.label_53.setText(_translate("Dialog", "5v", None))
        self.label_57.setText(_translate("Dialog", "General-Purpose I/O Pin", None))
        self.label_59.setText(_translate("Dialog", "GPIO", None))
        self.label_54.setText(_translate("Dialog", "Toprak (Ground) Pini", None))
        self.label_56.setText(_translate("Dialog", "GND", None))

