# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/tasarim.ui'
#
# Created: Wed Jul 22 23:51:51 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setEnabled(True)
        Dialog.resize(461, 400)
        Dialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.horizontalLayoutWidget = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 201, 381))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.checkBox_2 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.verticalLayout_4.addWidget(self.checkBox_2)
        self.checkBox_21 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_21.setObjectName(_fromUtf8("checkBox_21"))
        self.verticalLayout_4.addWidget(self.checkBox_21)
        self.checkBox_22 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_22.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_22.setObjectName(_fromUtf8("checkBox_22"))
        self.verticalLayout_4.addWidget(self.checkBox_22)
        self.checkBox_23 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_23.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_23.setObjectName(_fromUtf8("checkBox_23"))
        self.verticalLayout_4.addWidget(self.checkBox_23)
        self.checkBox_32 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_32.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_32.setObjectName(_fromUtf8("checkBox_32"))
        self.verticalLayout_4.addWidget(self.checkBox_32)
        self.checkBox_31 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_31.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_31.setObjectName(_fromUtf8("checkBox_31"))
        self.verticalLayout_4.addWidget(self.checkBox_31)
        self.checkBox_13 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.verticalLayout_4.addWidget(self.checkBox_13)
        self.checkBox_30 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_30.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_30.setObjectName(_fromUtf8("checkBox_30"))
        self.verticalLayout_4.addWidget(self.checkBox_30)
        self.checkBox_29 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_29.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_29.setObjectName(_fromUtf8("checkBox_29"))
        self.verticalLayout_4.addWidget(self.checkBox_29)
        self.checkBox_28 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_28.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_28.setObjectName(_fromUtf8("checkBox_28"))
        self.verticalLayout_4.addWidget(self.checkBox_28)
        self.checkBox_45 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_45.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_45.setObjectName(_fromUtf8("checkBox_45"))
        self.verticalLayout_4.addWidget(self.checkBox_45)
        self.checkBox_46 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_46.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_46.setObjectName(_fromUtf8("checkBox_46"))
        self.verticalLayout_4.addWidget(self.checkBox_46)
        self.checkBox_27 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_27.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_27.setObjectName(_fromUtf8("checkBox_27"))
        self.verticalLayout_4.addWidget(self.checkBox_27)
        self.checkBox_26 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_26.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_26.setObjectName(_fromUtf8("checkBox_26"))
        self.verticalLayout_4.addWidget(self.checkBox_26)
        self.checkBox_25 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_25.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_25.setObjectName(_fromUtf8("checkBox_25"))
        self.verticalLayout_4.addWidget(self.checkBox_25)
        self.checkBox_24 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_24.setObjectName(_fromUtf8("checkBox_24"))
        self.verticalLayout_4.addWidget(self.checkBox_24)
        self.checkBox_14 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_14.setObjectName(_fromUtf8("checkBox_14"))
        self.verticalLayout_4.addWidget(self.checkBox_14)
        self.checkBox_19 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_19.setObjectName(_fromUtf8("checkBox_19"))
        self.verticalLayout_4.addWidget(self.checkBox_19)
        self.checkBox_17 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_17.setObjectName(_fromUtf8("checkBox_17"))
        self.verticalLayout_4.addWidget(self.checkBox_17)
        self.checkBox_16 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_16.setObjectName(_fromUtf8("checkBox_16"))
        self.verticalLayout_4.addWidget(self.checkBox_16)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkBox_15 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_15.setObjectName(_fromUtf8("checkBox_15"))
        self.verticalLayout_3.addWidget(self.checkBox_15)
        self.checkBox_43 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_43.setObjectName(_fromUtf8("checkBox_43"))
        self.verticalLayout_3.addWidget(self.checkBox_43)
        self.checkBox_42 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_42.setObjectName(_fromUtf8("checkBox_42"))
        self.verticalLayout_3.addWidget(self.checkBox_42)
        self.checkBox_41 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_41.setObjectName(_fromUtf8("checkBox_41"))
        self.verticalLayout_3.addWidget(self.checkBox_41)
        self.checkBox_40 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_40.setObjectName(_fromUtf8("checkBox_40"))
        self.verticalLayout_3.addWidget(self.checkBox_40)
        self.checkBox_39 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_39.setObjectName(_fromUtf8("checkBox_39"))
        self.verticalLayout_3.addWidget(self.checkBox_39)
        self.checkBox_38 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_38.setObjectName(_fromUtf8("checkBox_38"))
        self.verticalLayout_3.addWidget(self.checkBox_38)
        self.checkBox_37 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_37.setObjectName(_fromUtf8("checkBox_37"))
        self.verticalLayout_3.addWidget(self.checkBox_37)
        self.checkBox_36 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_36.setObjectName(_fromUtf8("checkBox_36"))
        self.verticalLayout_3.addWidget(self.checkBox_36)
        self.checkBox_35 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_35.setObjectName(_fromUtf8("checkBox_35"))
        self.verticalLayout_3.addWidget(self.checkBox_35)
        self.checkBox_47 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_47.setObjectName(_fromUtf8("checkBox_47"))
        self.verticalLayout_3.addWidget(self.checkBox_47)
        self.checkBox_48 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_48.setObjectName(_fromUtf8("checkBox_48"))
        self.verticalLayout_3.addWidget(self.checkBox_48)
        self.checkBox_34 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_34.setObjectName(_fromUtf8("checkBox_34"))
        self.verticalLayout_3.addWidget(self.checkBox_34)
        self.checkBox_33 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_33.setObjectName(_fromUtf8("checkBox_33"))
        self.verticalLayout_3.addWidget(self.checkBox_33)
        self.checkBox_18 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_18.setObjectName(_fromUtf8("checkBox_18"))
        self.verticalLayout_3.addWidget(self.checkBox_18)
        self.checkBox_11 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.verticalLayout_3.addWidget(self.checkBox_11)
        self.checkBox_20 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_20.setObjectName(_fromUtf8("checkBox_20"))
        self.verticalLayout_3.addWidget(self.checkBox_20)
        self.checkBox_12 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.verticalLayout_3.addWidget(self.checkBox_12)
        self.checkBox = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.verticalLayout_3.addWidget(self.checkBox)
        self.checkBox_44 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_44.setObjectName(_fromUtf8("checkBox_44"))
        self.verticalLayout_3.addWidget(self.checkBox_44)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayoutWidget_3 = QtGui.QWidget(Dialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(220, 10, 231, 381))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.btn_ac = QtGui.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ac.sizePolicy().hasHeightForWidth())
        self.btn_ac.setSizePolicy(sizePolicy)
        self.btn_ac.setObjectName(_fromUtf8("btn_ac"))
        self.horizontalLayout_16.addWidget(self.btn_ac)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btn_ac_3 = QtGui.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ac_3.sizePolicy().hasHeightForWidth())
        self.btn_ac_3.setSizePolicy(sizePolicy)
        self.btn_ac_3.setObjectName(_fromUtf8("btn_ac_3"))
        self.horizontalLayout_3.addWidget(self.btn_ac_3)
        self.btn_ac_2 = QtGui.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ac_2.sizePolicy().hasHeightForWidth())
        self.btn_ac_2.setSizePolicy(sizePolicy)
        self.btn_ac_2.setObjectName(_fromUtf8("btn_ac_2"))
        self.horizontalLayout_3.addWidget(self.btn_ac_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_50 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.horizontalLayout_17.addWidget(self.label_50)
        self.label_49 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.horizontalLayout_17.addWidget(self.label_49)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_51 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.horizontalLayout_18.addWidget(self.label_51)
        self.label_53 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.horizontalLayout_18.addWidget(self.label_53)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_57 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.horizontalLayout_20.addWidget(self.label_57)
        self.label_59 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.horizontalLayout_20.addWidget(self.label_59)
        self.verticalLayout_6.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_54 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.horizontalLayout_19.addWidget(self.label_54)
        self.label_56 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.horizontalLayout_19.addWidget(self.label_56)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.checkBox_2.setText(_translate("Dialog", "5v", None))
        self.checkBox_21.setText(_translate("Dialog", "5v", None))
        self.checkBox_22.setText(_translate("Dialog", "GND", None))
        self.checkBox_23.setText(_translate("Dialog", "GPIO 14", None))
        self.checkBox_32.setText(_translate("Dialog", "GPIO 15", None))
        self.checkBox_31.setText(_translate("Dialog", "GPIO 18", None))
        self.checkBox_13.setText(_translate("Dialog", "GND", None))
        self.checkBox_30.setText(_translate("Dialog", "GPIO 23", None))
        self.checkBox_29.setText(_translate("Dialog", "GPIO 24", None))
        self.checkBox_28.setText(_translate("Dialog", "GND", None))
        self.checkBox_45.setText(_translate("Dialog", "GPIO 25", None))
        self.checkBox_46.setText(_translate("Dialog", "GPIO 08", None))
        self.checkBox_27.setText(_translate("Dialog", "GPIO 07", None))
        self.checkBox_26.setText(_translate("Dialog", "ID_SC", None))
        self.checkBox_25.setText(_translate("Dialog", "GND", None))
        self.checkBox_24.setText(_translate("Dialog", "GPIO 12", None))
        self.checkBox_14.setText(_translate("Dialog", "GND", None))
        self.checkBox_19.setText(_translate("Dialog", "GPIO 16", None))
        self.checkBox_17.setText(_translate("Dialog", "GPIO 20", None))
        self.checkBox_16.setText(_translate("Dialog", "GPIO 21", None))
        self.checkBox_15.setText(_translate("Dialog", "3v3", None))
        self.checkBox_43.setText(_translate("Dialog", "GPIO 02", None))
        self.checkBox_42.setText(_translate("Dialog", "GPIO 03", None))
        self.checkBox_41.setText(_translate("Dialog", "GPIO 04", None))
        self.checkBox_40.setText(_translate("Dialog", "GND", None))
        self.checkBox_39.setText(_translate("Dialog", "GPIO 17", None))
        self.checkBox_38.setText(_translate("Dialog", "GPIO 27", None))
        self.checkBox_37.setText(_translate("Dialog", "GPIO 22", None))
        self.checkBox_36.setText(_translate("Dialog", "3v3", None))
        self.checkBox_35.setText(_translate("Dialog", "GPIO 10", None))
        self.checkBox_47.setText(_translate("Dialog", "GPIO 09", None))
        self.checkBox_48.setText(_translate("Dialog", "GPIO 11", None))
        self.checkBox_34.setText(_translate("Dialog", "GND", None))
        self.checkBox_33.setText(_translate("Dialog", "ID_SD", None))
        self.checkBox_18.setText(_translate("Dialog", "GPIO 05", None))
        self.checkBox_11.setText(_translate("Dialog", "GPIO 06", None))
        self.checkBox_20.setText(_translate("Dialog", "GPIO 13", None))
        self.checkBox_12.setText(_translate("Dialog", "GPIO 19", None))
        self.checkBox.setText(_translate("Dialog", "GPIO 26", None))
        self.checkBox_44.setText(_translate("Dialog", "GND", None))
        self.btn_ac.setText(_translate("Dialog", "Uygula", None))
        self.btn_ac_3.setText(_translate("Dialog", "Kapat", None))
        self.btn_ac_2.setText(_translate("Dialog", "Bilgi", None))
        self.label_50.setText(_translate("Dialog", "       3,3 V Çıkış Pini", None))
        self.label_49.setText(_translate("Dialog", "3v3", None))
        self.label_51.setText(_translate("Dialog", "           5 V Çıkış Pini", None))
        self.label_53.setText(_translate("Dialog", "5v", None))
        self.label_57.setText(_translate("Dialog", "General-Purpose I/O Pin", None))
        self.label_59.setText(_translate("Dialog", "GPIO", None))
        self.label_54.setText(_translate("Dialog", "Toprak (Ground) Pini", None))
        self.label_56.setText(_translate("Dialog", "GND", None))

